<main id="faq">
    <figure>
        <img src="/www/img/illus_faq.jpg" alt="Illustration">
    </figure>
    
    <section>
        <h2>Qu’est-ce qu’un photographe de mariage ?</h2>
        <div>
            <p>Un photographe de mariage est un photographe qui s’est spécialisé dans un style de photographie particulier : le reportage. Mais il doit être aussi capable de réaliser des portraits, des photos de groupe posées. En outre, un photographe de mariage doit avoir un sens aigu du relationnel car la relation particulière entre les mariés et le photographe ne s’établi qu’à condition qu’ils soient en confiance. Pour résumer, un photographe de mariage est un photographe qui doit savoir travailler aussi bien dans la précipitation d’une journée de festivité que savoir arrêter le temps à certains moments, pour faire transparaître les émotions.</p>
        </div>
    </section>
    
    <section>
        <h2>Proposez-vous plusieurs types de forfaits ?</h2>
        <div>
            <p>Bien évidement, chaque couple a des attentes et des budgets bien différents. Ainsi, nous proposons quatre types de prestation allant de la formule « argent » à la formule « diamant », pour s’adapter au mieux à l’attente de chaque client.</p>
        </div>
    </section>
    
    <section>
        <h2>Combien de photographies réalisez-vous lors d’un mariage ?</h2>
        <div>
            <p>Le nombre de photos prises varie quelque peu entre chaque mariage, mais nous prenons généralement autour de 1000 à 1500 photos par photographe pour une journée complète. En revanche, le tri effectué par la suite ramènera à quelques 500 photos livrées par photographe environ.</p>
        </div>
    </section>
    
    <section>
        <h2>Peut-on avoir le DVD ?</h2>
        <div>
            <p>Il est  nous est tout à fait possible de livrer les photos sur un support DVD ou même une clef USB.</p>
        </div>
    </section>
    
    <section>
        <h2>Pourrons-nous avoir les photographies en noir et blanc ?</h2>
        <div>
            <p>Nous avons pour habitude de traiter les photos en couleur mais aussi en noir et blanc, lorsque celles-ci s’y prêtent. Vous aurez donc des photos en couleur et en noir et blanc livrées.</p>
        </div>
    </section>
    
    <section>
        <h2>Comment pourrons-nous faire notre sélection de photo ?</h2>
        <div>
            <p>Pour différentes raisons, il n’est pas possible pour les mariés de faire une séléction préalable des photos qui seront traitées par nos soins. La sélection que nous faisons fait partie intégrante de notre prestation. Cette sélection consiste principalement à supprimer les photos trop sombres ou « cramées » (trop de lumière) ainsi que de repérer les détails gênants qui peuvent apparaitre pour que la sélection finale soit la plus belle et la plus représentative possible. En revanche, il est tout a fait possible, pour les mariés, de procéder à la sélection des images qui iront illustrer leur album imprimé.</p>
        </div>
    </section>
    
    <section>
        <h2>Peut-on faire des photos avant ou après le mariage ?</h2>
        <div>
            <p>Il est tout à fait possible de faire des photos avant ET après le mariage. Nous avons l’habitude de proposer une séance « engagement » ou pré-shoot bien avant le mariage pour que le couple se familiarise avec le ou les photographes, facilitant ainsi la futur relation privilégiée entre nous et les mariés le jour J.

            Nous proposons aussi, en option, une séance qui sera faite le lendemain de la cérémonie, communément appelé « Trash the dress » qui consiste à placer les époux dans des situations cocasses et décalées ou simplement de compléter la séance de prise de vues en tenue de mariés dans des endroits insolites ou hors du commun.</p>
        </div>
    </section>
    
    <section>
        <h2>Notre cérémonie (civile ou religieuse) est décalée… Pouvez-vous être présent ?</h2>
        <div>
            <p>Oui, à condition que nous soyons prévenus suffisamment tôt, pour que nous puissions prendre nos dispositions. Notre emploi du temps ne nous permettant pas de fluctuations trop importantes.</p>
        </div>
    </section>
    
    <section>
        <h2>Travaillez-vous avec un vidéaste pour réaliser notre reportage vidéo de mariage ?</h2>
        <div>
            <p>Pour le moment, nous avons décidé de ne pas travailler avec quelqu’un d’extérieur à Photographe-2-Mariage pour des raisons de cohésion et de méthodes de travail. Un mariage est un moment important et la réussite des images impose de réduire au maximum les aléas. Nous proposons, en revanche, de fournir nous même une prestation vidéo si vous le voulez. Nous avons les connaissances ainsi que le matériel nécessaire. Dans ce cas de figure, un des deux photographes présent se transforme en vidéaste pour la journée.</p>
        </div>
    </section>
    
    <section>
        <h2>Comment pouvons-nous réserver votre présence pour réaliser le reportage photo de notre mariage ?</h2>
        <div>
            <p>Il suffit de nous envoyer un mail avec la ou les dates de votre mariage ou même, si vous préférez, de nous appeler directement. Nous vous répondrons sous 72 heures maximum.</p>
        </div>
    </section>
    
    <section>
        <h2>Comment vos tarifs sont-ils calculés ?</h2>
        <div>
            <p>Nos tarifs sont calculés sur une base horaire ainsi que sur quelques autres critères. Pour les précisions , nous vous invitons à consulter cet excellent article qui explique précisément les prix d’un photographe de mariage :</p>
            <p>Un mariage d'une journée avec un livre de mariage à 1200€</p><br>
            <p>Pour un mariage d'une journée voici ce qu'il faut compter : </p>
            <ul>
                <li>20 minutes de réponse à la demande du client (mail + téléphone + rencontre)</li>
                <li>1h30 d'entrevue avec le client</li>
                <li>1h30 pour un second rendez-vous et la signature du contrat</li>
                <li>Réponse aux questions supplémentaires des mariés par mail ou téléphone 1h</li>
                <li>Séance photo pour préparation du mariage 1h30</li>
                <li>45 minutes de préparation du matériel</li>
                <li>1h de voyage pour aller au mariage et arriver avant l'heure</li>
                <li>Prestation du mariage 15h</li>
                <li>1h de retour du mariage</li>
                <li>Vidage des cartes mémoires 1h</li>
                <li>1h pour faire les sauvegardes sur plusieurs disques</li>
                <li>4h pour le tri des photos</li>
                <li>Traitement des photos de 5h à 7h</li>
                <li>Création de la galerie privée en ligne - 30 minutes</li>
                <li>Création du CD + envoi - 1h</li>
                <li>Création du livre photo 4h</li>
            </ul>
            <p>Total des heures de travail pour un mariage avec un reportage de 10h et un livre photo 42h soit une semaine de travail environ.</p><br>
            <p>Ce qu'il vous faut enlever du tarif comme frais :</p>
            <ul>
                <li>La TVA 19,6% soit 196,66€</li>
                <li>Le déplacement + le matériel + les disques pour la sauvegarde + les services pour la galerie privée + les assurances + ... 100€</li>
                <li>Achat du livre photo 200€</li>
                <li>Les divers Taxes soit 200,96€ (40% sur le net, donc sur le prix HT - les frais)</li>
                <li>Il reste donc 1200€ - (196,66€ + 100€ + 200€ + 200,96€) = 502,39€ pour disons 42h de travail pour 11,96€/h (Le smic est à 9,43€).</li>
            </ul>

            <p>N'oubliez pas que ce tarif est le taux horaire brut. Il intègre les 5h de vacances que tous les salarié ont pour 42h de travail, mais aussi votre retraite.</p>

            <p>Donc même sans la retraite en net cela donne 502,39€ pour 42h de travail + 5h de vacances soit 516,67€/47h = 10,69€/heure au quel il faut encore enlever le coût de votre retraite et votre assurance santé.</p>

            <p>Donc pour un mariage à 1200€ le tarif horaire du photographe est de 113% du smic. Pour ce tarif horaire légèrement au dessus du smic vous avez la responsabilité d'arriver à l'heure, de faire de belles photos, de ne rien louper, de ne pas avoir de matériel défaillant et vos 10 ans d'expérience en photo. En gros le travail d'un cadre, payer 113% du smic horaire.</p>

            <p>Pour le même mariage à 1500€ vous arrivez à un taux horaire de 14,50€/h soit 154% du smic.</p>
            <a href="http://blog.deviens-photographe.com/index.php/2013/05/je-veux-devenir-photographe-67-donner-une-valeur-a-son-travail/#sthash.pYH8ReCd.dpuf">Voir l'article Source</a>
        </div>
    </section>
    
    <section>
        <h2>Y a-t-il des frais de déplacement ?</h2>
        <div>
            <p>Pour les mariages en ile-de-France, aucun frais ne seront demandés. Hors d’ile-de-France, nous ajoutons les frais de train ou, le cas échéant, d’avion à notre prestation.</p>
        </div>
    </section>
    
    <section>
        <h2>Vous déplacez vous partout en France et à l’étranger ? Jusqu’où ?</h2>
        <div>
            <p>Nous pouvons nous déplacer aussi loin que notre agenda et votre budget nous le permet. Vous vous mariez en Nouvelle-Calédonie et vous nous voulez pour votre mariage ? Si nous avons le temps et que vous avez les moyens, pas de problème.</p>
        </div>
    </section>
    
    <section>
        <h2>Quand et comment devons-nous vous régler ?</h2>
        <div>
            <p>Nous aimons que les choses soient simples et claires : nous demandons un acompte de 30% à la réservation, et le reste du paiement sera fait à la livraison des photos.</p>
        </div>
    </section>
    
    <section>
        <h2>Pouvons-nous régler en plusieurs fois ?</h2>
        <div>
            <p>Nous sommes en train de mettre en place un système vous permettant de régler en plusieurs fois. Ce qui peut vous permettre de réserver une formule de prestation supérieure et de ne pas vous soucier d’avoir à sortir une somme trop importante en une fois.</p>
        </div>
    </section>
    
    <section>
        <h2>Combien de temps faudra-t’il que nous prévoyons pour les photos de couple ?</h2>
        <div>
            <p>Habituellement, nous prenons environ 1h à 1h30 pour réaliser les photos de couple dans une ambiance détendue, gage de photos réussies.</p>
        </div>
    </section>
    
    <section>
        <h2>Où ferons-nous nos photos de couple ?</h2>
        <div>
            <p>Où vous le souhaitez. Si vous n’avez pas d’idée, nous en aurons, ne vous en faites pas.</p>
        </div>
    </section>
    
    <section>
        <h2>Que prévoyez-vous si la météo est catastrophique ?</h2>
        <div>
            <p>Nous avons l’habitude de composer avec une météo aléatoire. Cela fait partie des imprévus que nous tentons de prévoir. Et il y a toujours une solution simple à portée de main.</p>
        </div>
    </section>
    
    <section>
        <h2>Jusqu’à quelle heure resterez-vous parmi-nous ?</h2>
        <div>
            <p>Cela dépend de vous. Nous restons aussi longtemps que vous le souhaitez. En général, nous arrêtons de prendre des photos à 22h ou vers 1h, en fonction de la présence d’une pièce-montée.</p>
        </div>
    </section>
    
    <section>
        <h2>Serait-il possible que vous présentiez des photos de notre mariage le soir même ?</h2>
        <div>
            <p>Par amour des choses bien faites, nous ne faisons pas de projections de photo le soir même. Nous préférons que le traitement des images soit optimal avant que quiconque les voient.</p>
        </div>
    </section>
    
    <section>
        <h2>Combien de temps faut-il compter pour obtenir nos photos ? Quid des délais de livraison ?</h2>
        <div>
            <p>Il faut compter entre 3 semaines et 1 mois pour la livraison des images finalisées.</p>
        </div>
    </section>
    
    <section>
        <h2>Nos proches et amis pourront-ils consulter votre travail et commander des photos ?</h2>
        <div>
            <p>Nous travaillons en ce moment à ce que vous et vos proches puissiez voir les images directement sur notre site, ainsi que la possibilité de passer des commandes d’impression de photo directement depuis le site Photographe-2-Mariage.com</p>
        </div>
    </section>
    
    <section>
        <h2>Avec quel matériel travaillez-vous ?</h2>
        <div>
            <p>Nous travaillons avec différents appareils, deux canon, 5D et 6D, ainsi qu'un boitier Sony A7s et un Panasonic GH4.</p>
            <p>Quand aux optiques, nous travaillons avec des objectifs haut-de-gamme :</p>
            <ul>
                <li>Canon 16-35 mm f2.8 II L</li>
                <li>Tamron 24-70 mm f2.8 VC</li>
                <li>Canon 50mm f1.4 USM</li>
                <li>Canon 100 mm f2.8 IS L</li>
                <li>Canon 70-200 mm f2.8</li>
            </ul>
        </div>
    </section>
    
    <section>
        <h2>Travaillez-vous en numérique ou en argentique ?</h2>
        <div>
            <p>Nous travaillons exclusivement en numérique.</p>
        </div>
    </section>
    
    <section>
        <h2>Les photos sont-elles retouchées ?</h2>
        <div>
            <p>Un fois la sélection effectuée, nous retouchons nos images. Ces retouches vont de la simple mise en noir et blanc, à la retouche complexe sous photoshop.</p>
        </div>
    </section>
    
</main>